name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Atualiza todo dia à meia-noite
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main               # Atualiza quando fizer push no README

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: yes
